version: "3.4"

services:
  maria-db:
    image: mariadb
    volumes:
      - "./db/mariadb:/docker-entrypoint-initdb.d"
    networks:
      - default
    ports:
      - "9081:3306"
    environment:
      #- "MARIADB_USER=root"
      - "MARIADB_ROOT_PASSWORD=admin_pass"
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

  mysql-db:
    image: mysql
    volumes:
      - "./db/mysql:/docker-entrypoint-initdb.d"
    networks:
      - default
    ports:
      - "9083:3306"
    environment:
      #- "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=admin_pass"
    command: --default-authentication-plugin=mysql_native_password

  postgres-db:
    image: postgres
    volumes:
      - "./db/postgres:/docker-entrypoint-initdb.d"
    networks:
      - default
    ports:
      - "9084:5432"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin_pass"

  mongo-db:
    image: mongo
    networks:
      - default
    ports:
      - "9085:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=admin_pass"

  redis-db:
    image: redis:alpine
    networks:
      - default
    ports:
      - "9086:6379"

  sql-ui:
    image: adminer
    restart: always
    networks:
      - default
    ports:
      - "8080:8080"
    depends_on:
      - maria-db
      - mysql-db
      - postgres-db

  mongo-ui:
    image: mongo-express
    restart: always
    networks:
      - default
    ports:
      - "8081:8081"
    environment:
      - "ME_CONFIG_MONGODB_SERVER=mongo-db"
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=admin"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=admin_pass"
    depends_on:
      - mongo-db

  redis-ui:
    image: rediscommander/redis-commander
    restart: always
    networks:
      - default
    ports:
      - "8082:8081"
    environment:
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis-db"
    depends_on:
      - redis-db
