name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Switch to nightly channel
        run: rustup toolchain install nightly --allow-downgrade -c rustfmt

      - name: Check Formatting
        run: make check_fmt

  build:
    name: Build and Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Build Doc
        run: make doc

      - name: Run Tests
        run: make up && sleep 120 && make test
